#!/bin/bash

clear

service_name=senti-watchman.service
service_dir=/etc/systemd/system
server_dir=/srv/nodejs/senti/senti-watchman

service=$service_dir/$service_name

echo Registering Watchman service ...

if [ ! -e "$service" ]; then
	echo
    echo "Watchman service is not installed"
	echo "Installing Watchman service ..."
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service_name ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service_name ..."
	sudo systemctl start $service_name
else 
    echo "Watchman service is already installed"
	echo "Enabling $service_name ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service_name ..."
	sudo systemctl stop $service_name
	sudo systemctl start $service_name
fi 
